_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-aarch64
AlphaGRAD:
    value: true
always_save_checkpoint:
    value: true
backend:
    value: nccl
batch_size:
    value: 12
beta1:
    value: 0.9
beta2:
    value: 0.95
bias:
    value: true
block_size:
    value: 1024
compile:
    value: false
d_reduction_factor:
    value: 2
dataset:
    value: openwebtext
decay_lr:
    value: true
device:
    value: cuda
dropout:
    value: 0
dtype:
    value: bfloat16
eval_interval:
    value: 1000
eval_iters:
    value: 200
eval_only:
    value: false
gating_d_new:
    value: null
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 40
hellaswag:
    value: false
hellaswag_path:
    value: data/hellaswag/hellaswag_val.jsonl
init_from:
    value: scratch
learning_rate:
    value: 0.0004
log_interval:
    value: 10
lr_decay_iters:
    value: 600000
max_iters:
    value: 600000
min_lr:
    value: 6e-05
n_embd:
    value: 768
n_head:
    value: 16
n_layer:
    value: 12
out_dir:
    value: out
use_gated_reduction:
    value: false
user_config:
    value: reduc_2
wandb_log:
    value: true
wandb_project:
    value: owt
wandb_run_name:
    value: G-LMA
warmup_iters:
    value: 2000
weight_decay:
    value: 0.1
